name: emergixx_mobile
description: Emergixx - Enterprise-Grade Decentralized Emergency Communication Mobile Application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  emergixx_models:
    path: ../../packages/models
  emergixx_crypto:
    path: ../../packages/crypto
  emergixx_protocol:
    path: ../../packages/protocol
  emergixx_validation:
    path: ../../packages/validation
  emergixx_shared:
    path: ../../packages/shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
